Added YT channel info extractor
VeemsHQ/yt-channels-archive pull request #3
Opened 2021-01-29 18:34 UTC by bhartibhartendu

- Added YT channel extractor

2021-01-29 19:10 UTC, richardARPANET requested changes
Please can you add tests for this code then I'll review it

2021-02-01 07:35 UTC, richtier commented on requirements.txt
> +bs4==0.0.1
bs4 is proxy for beautifulsoup4. better to use beautifulsoup4 - that way unexpected stuff does not happen with the version

https://pypi.org/project/bs4/
https://pypi.org/project/beautifulsoup4/

2021-02-01 07:38 UTC, richtier commented on yt_archive/cli.py
> +def make_dir(_dir):
could use 
```
from pathlib import Path
Path(_dir).mkdir(parents=True, exist_ok=True)
```

the prefixed underscores reduce readability

2021-02-01 07:40 UTC, richtier commented on yt_archive/extractor.py
> +        return requests.get(self.yt_url).content
worth handling non 200 responses?

2021-02-01 10:13 UTC, richardARPANET commented
https://github.com/VeemsHQ/yt-channels-archive/pull/3#pullrequestreview-579541915

2021-02-01 10:40 UTC, bhartibhartendu commented on yt_archive/extractor.py
> +        return requests.get(self.yt_url).content
done

2021-02-01 10:40 UTC, bhartibhartendu commented on yt_archive/cli.py
> +def make_dir(_dir):
done

2021-02-01 10:40 UTC, bhartibhartendu commented on requirements.txt
> +bs4==0.0.1
done

2021-02-01 13:04 UTC, bhartibhartendu commented
Added test cases

2021-02-01 13:04 UTC, richardARPANET requested changes
Looks good, just a few minor comments ;)

2021-02-01 13:04 UTC, richardARPANET commented on yt_archive/extractor.py
> +            'www.youtube.com': YTExtractor(url)
what if the domain is `youtube.com` without the www?

2021-02-01 13:04 UTC, richardARPANET commented on tests/test_channel_info_extractor.py
> +    "https://www.youtube.com/channel/UCJ04m06GHw3DUDQG6chCAUA"
add in a few examples, with and without www

2021-02-01 13:04 UTC, richardARPANET commented on tests/test_channel_info_extractor.py
> +    "https://www.youtube.com/channel/UCJ04m06GHw3DUDQG6chCAUA"
also, TEST_YT_URLS makes more sense as a var name since it's a list

2021-02-01 13:04 UTC, richardARPANET commented on tests/test_channel_info_extractor.py
> +    for i in range(0, len(TEST_YT_URL)):
instead of a loop within the test, it would be better to use https://docs.pytest.org/en/stable/parametrize.html

e.g.

```python
@pytest.mark.parametrize('url', TEST_YT_URLS)
def test_channel_info_cli(url):
    ...
```

2021-02-01 14:40 UTC, bhartibhartendu commented on yt_archive/extractor.py
> +            'www.youtube.com': YTExtractor(url)
it will pick the default YTExtractor

2021-02-01 14:40 UTC, bhartibhartendu commented on tests/test_channel_info_extractor.py
> +    "https://www.youtube.com/channel/UCJ04m06GHw3DUDQG6chCAUA"
done

2021-02-01 14:40 UTC, richardARPANET approved these changes

2021-02-01 14:41 UTC, bhartibhartendu commented on yt_archive/cli.py
> +        urllib.request.urlretrieve(channel_info['banner_image'],
done

2021-02-01 14:41 UTC, bhartibhartendu commented on yt_archive/extractor.py
> +            'www.youtube.com': YTExtractor(url)
it will pick default YT extractor

2021-02-01 14:41 UTC, richardARPANET commented
@bhartibhartendu I'll merge this, and later today try out running it and let you know

2021-02-01 14:43 UTC, merged

2021-02-01 19:52 UTC, richardARPANET commented
Working well so far :+1: